services:
  client:
    image: ${CLIENT_IMAGE:-ghcr.io/praveenkurupati/perfectpic-client:latest}
    restart: always
    ports: !override []
    deploy:
      resources:
        limits:
          memory: 350M
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  admin:
    image: ${ADMIN_IMAGE:-ghcr.io/praveenkurupati/perfectpic-admin:latest}
    restart: always
    ports: !override []
    deploy:
      resources:
        limits:
          memory: 250M
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  backend:
    image: ${BACKEND_IMAGE:-ghcr.io/praveenkurupati/perfectpic-backend:latest}
    restart: always
    ports: !override []
    volumes:
      - uploads_data:/app/uploads
    deploy:
      resources:
        limits:
          memory: 250M
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  mongodb:
    restart: always
    ports: !override []
    deploy:
      resources:
        limits:
          memory: 350M
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  redis:
    restart: always
    ports: !override []
    deploy:
      resources:
        limits:
          memory: 100M
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  nginx:
    restart: always
    ports:
      - "80:80"
      - "443:443"
    deploy:
      resources:
        limits:
          memory: 80M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"

volumes:
  uploads_data:
    name: perfectpic_uploads_data
