#!/usr/bin/env bash
# ==============================================================================
# PerfectPic Enterprise MongoDB Automated Backup & 30-Day Retention Pruner
# ==============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
BACKUP_DIR="${ROOT_DIR}/backups/mongodb"
RETENTION_DAYS="${BACKUP_RETENTION_DAYS:-30}"

mkdir -p "${BACKUP_DIR}"

# 1. Load environment variables
if [ -f "${ROOT_DIR}/.env" ]; then
  # shellcheck disable=SC1091
  source "${ROOT_DIR}/.env"
elif [ -f "${ROOT_DIR}/apps/backend/.env" ]; then
  # shellcheck disable=SC1091
  source "${ROOT_DIR}/apps/backend/.env"
fi

MONGO_URI="${MONGODB_URI:-${MONGO_URI:-mongodb://localhost:27017/perfectpic}}"
TIMESTAMP=$(date +"%Y-%m-%d-%H%M%S")
BACKUP_NAME="perfectpic-mongodb-backup-${TIMESTAMP}"
ARCHIVE_PATH="${BACKUP_DIR}/${BACKUP_NAME}.tar.gz"
META_PATH="${BACKUP_DIR}/${BACKUP_NAME}.meta.json"

echo "======================================================================"
echo "📦 [MongoDB Backup] Starting automated backup at $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
echo "   Target Archive: ${ARCHIVE_PATH}"
echo "   Retention Window: ${RETENTION_DAYS} days"
echo "======================================================================"

# 2. Check if mongodump is available and reachable
DUMP_SUCCESS=false
if command -v mongodump >/dev/null 2>&1; then
  echo "🔍 Checking native mongodump reachability..."
  TEMP_DUMP_DIR="${BACKUP_DIR}/tmp_${TIMESTAMP}"
  mkdir -p "${TEMP_DUMP_DIR}"
  
  # Append fast timeout parameters if not already in URI
  FAST_URI="${MONGO_URI}"
  if [[ "${FAST_URI}" != *"serverSelectionTimeoutMS"* ]]; then
    if [[ "${FAST_URI}" == *"?"* ]]; then
      FAST_URI="${FAST_URI}&serverSelectionTimeoutMS=2000&connectTimeoutMS=2000"
    else
      FAST_URI="${FAST_URI}?serverSelectionTimeoutMS=2000&connectTimeoutMS=2000"
    fi
  fi

  if mongodump --uri="${FAST_URI}" --query="{}" --out="${TEMP_DUMP_DIR}" --gzip 2>/dev/null; then
    tar -czf "${ARCHIVE_PATH}" -C "${TEMP_DUMP_DIR}" .
    rm -rf "${TEMP_DUMP_DIR}"
    DUMP_SUCCESS=true
    echo "✅ Native mongodump completed successfully."
  else
    rm -rf "${TEMP_DUMP_DIR}"
    echo "⚠️ Native mongodump connection unreachable. Cascading to Node.js BackupService engine..."
  fi
fi

if [ "$DUMP_SUCCESS" = false ]; then
  echo "🚀 Executing Node.js BackupService engine..."
  cd "${ROOT_DIR}"
  ./apps/backend/node_modules/.bin/tsx apps/backend/src/scripts/run-backup.ts
  
  # Find latest archive generated by BackupService
  LATEST_ARCHIVE=$(find "${BACKUP_DIR}" -type f -name "perfectpic-mongodb-backup-*.tar.gz" | sort | tail -n 1)
  if [ -z "${LATEST_ARCHIVE}" ]; then
    echo "❌ Error: Backup archive was not created by Node engine."
    exit 1
  fi
  ARCHIVE_PATH="${LATEST_ARCHIVE}"
  BACKUP_NAME=$(basename "${ARCHIVE_PATH}" .tar.gz)
  META_PATH="${BACKUP_DIR}/${BACKUP_NAME}.meta.json"
fi

# 3. Calculate SHA-256 and File Size
FILE_SIZE_BYTES=$(stat -f%z "${ARCHIVE_PATH}" 2>/dev/null || stat -c%s "${ARCHIVE_PATH}" 2>/dev/null || wc -c < "${ARCHIVE_PATH}")
FILE_SIZE_MB=$(awk "BEGIN {printf \"%.2f\", ${FILE_SIZE_BYTES}/1048576}")
SHA256_HASH=$(shasum -a 256 "${ARCHIVE_PATH}" 2>/dev/null | awk '{print $1}' || sha256sum "${ARCHIVE_PATH}" 2>/dev/null | awk '{print $1}' || echo "n/a")
EXPIRY_DATE=$(date -v+"${RETENTION_DAYS}"d +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date -d "+${RETENTION_DAYS} days" +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || echo "in-${RETENTION_DAYS}-days")

# 4. Generate Metadata Manifest if not created by Node engine
if [ ! -f "${META_PATH}" ]; then
  cat <<EOF > "${META_PATH}"
{
  "backupId": "${BACKUP_NAME}",
  "filename": "${BACKUP_NAME}.tar.gz",
  "createdAt": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "formattedDate": "$(date +"%Y-%m-%d %H:%M:%S")",
  "sizeBytes": ${FILE_SIZE_BYTES},
  "sizeMb": ${FILE_SIZE_MB},
  "sha256": "${SHA256_HASH}",
  "retentionDays": ${RETENTION_DAYS},
  "expiresAt": "${EXPIRY_DATE}",
  "status": "completed"
}
EOF
fi

echo "✅ Backup successfully created!"
echo "   Archive: ${BACKUP_NAME}.tar.gz (${FILE_SIZE_MB} MB)"
echo "   SHA256:  ${SHA256_HASH}"
echo "   Expires: ${EXPIRY_DATE}"

# 5. Enforce 30-Day Retention Policy (Automatic Pruning)
echo "🧹 [Retention Manager] Pruning backup archives older than ${RETENTION_DAYS} days..."
PRUNED_COUNT=0

# Delete archives older than retention days
find "${BACKUP_DIR}" -type f -name "perfectpic-mongodb-backup-*.tar.gz" -mtime +"${RETENTION_DAYS}" -print | while read -r old_archive; do
  echo "   Deleting expired archive: $(basename "${old_archive}")"
  rm -f "${old_archive}"
  rm -f "${old_archive%.tar.gz}.meta.json"
  PRUNED_COUNT=$((PRUNED_COUNT + 1))
done

find "${BACKUP_DIR}" -type f -name "perfectpic-mongodb-backup-*.meta.json" -mtime +"${RETENTION_DAYS}" -delete 2>/dev/null || true

echo "✨ Retention check complete. Pruned ${PRUNED_COUNT} expired backups."

# 6. Optional S3 Cloud Sync if configured
if [ -n "${AWS_S3_BACKUP_BUCKET:-}" ] && command -v aws >/dev/null 2>&1; then
  echo "☁️ Uploading to Amazon S3 bucket: s3://${AWS_S3_BACKUP_BUCKET}/backups/mongodb/..."
  aws s3 cp "${ARCHIVE_PATH}" "s3://${AWS_S3_BACKUP_BUCKET}/backups/mongodb/${BACKUP_NAME}.tar.gz"
  aws s3 cp "${META_PATH}" "s3://${AWS_S3_BACKUP_BUCKET}/backups/mongodb/${BACKUP_NAME}.meta.json"
  echo "✅ S3 cloud mirror complete."
fi

echo "======================================================================"
echo "🎉 MongoDB automated backup process finished successfully!"
echo "======================================================================"
